spring:
  profiles:
    active: @smart.ENV@
  dubbox:
    registry:
       protocol: zookeeper   # 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是dubbo
          address: 192.168.1.8
          port: 2181
          client: curator  # zookeeper 支持客户端包括 curator和zkclient,如果不配置，默认使用zkclient
          register: true



