server:
  port: 0

spring:
  dubbox:
    registry:
      address: zookeeper://192.168.1.8:2181
      client: curator
#      session: -1
#      check: 
#      cluster: 
#      default: 
#      dynamic: 
#      file: 
#      group:
#      username:  
#      password: 
#      server: 
#      subscribe: 
#      timeout: 
#      transporter: 
#      version: 
#      parameters:
      
#    monitor:
#      protocol:
#      address:  
#      username: 
#      password: 
#      version: 
#      group: 
#      default: true
#      parameters:
#        test: test 

       
    protocols:
#      - name: dubbo
#        serialization: nativejava
#      - name: dubbo
#        serialization: hessian2
#      - name: dubbo
#        serialization: fastjson
#      - name: dubbo
#        serialization: jackson
#      - name: dubbo
#        serialization: dubbo
#      - name: dubbo
#        serialization: kryo
#        optimizer: com.laolei.dubbo.test.SerializationOptimizerImpl
      - name: dubbo
        serialization: fst
        optimizer: com.laolei.dubbo.test.SerializationOptimizerImpl
        
      - name: rest
        keep-alive: true
        server: netty
        iothreads: 5
        contextpath: /api
#      - name: rest
#        server: sunhttp
#        contextpath: /api
#      - name: rest
#        server: servlet
#        contextpath: /api
#      - name: rest
#        server: tomcat
#        accepts: 500
#        threads: 500
#        contextpath: /api
#        extension: com.alibaba.dubbo.rpc.protocol.rest.support.LoggingFilter

      - name: rmi
      - name: http
      - name: hessian
      
#      - name: webservice
#        accepts: 
#        accesslog: 
#        buffer: 
#        charset: 
#        client: 
#        codec: 
#        contextpath: 
#        default: 
#        dispatcher: 
#        exchanger: 
#        extension: 
#        heartbeat: 
#        host: 
#        iothreads: 
#        keep-alive: 
#        networker: 
#        optimizer: 
#        payload: 
#        prompt: 
#        queues: 
#        register: 
#        serialization: 
#        server: 
#        status: 
#        telnet: 
#        threadpool: 
#        threads: 
#        transporter: 
#        parameters:
