application:
  version: @project.version@
spring:
  profiles:
    active: @service.env@ #取配置文件
  datasource:   #数据库配置 DRUID
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  dubbox:
    scan: com.ybveg.govx.system.services
    provider:
      timeout : 30000
    protocols:    #使用dubbo协议
      - name: dubbo
        serialization: kryo
        optimizer: com.ybveg.govx.serialize.SerializationOptimizerImpl
    application:
      name: system-service@project.version@
      owner: zhangbinbin


mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql