spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/smart_dev
    username: smart
    password: yuanben

  dubbox:
    registry:
        protocol: zookeeper
        address: zookeeper://192.168.1.8:2181
        client: curator