spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/smart_dev?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true
    username: smart
    password: yuanben

  dubbox:
    registry:
      protocol: zookeeper
      address: zookeeper://192.168.1.8:2181
      client: curator
