
application:
  version: @project.version@
spring:
  profiles:
    active: @service.env@ #取配置文件
  datasource:   #数据库配置 DRUID
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  dubbox:
    scan: com.ybveg.govx.system.services
    provider:
      timeout : 30000
    protocols:    #使用dubbo协议
      - name: dubbo
        serialization: kryo
        optimizer: com.ybveg.dubbox.serialize.SerializationOptimizerImpl
    application:
      name: prota-web@project.version@
      owner: zhangbinbin
    serialize:    #序列化配置
      scan: com.ybveg.govx.**.model
      classes:
        - com.ybveg.auth.model.FunctionModel
        - com.ybveg.auth.model.ModuleModel
