server:
  port: 0
laolei:
  dubbox:
    application:
      name: demo-consumer
      owner: laolei
    base-package: com.laolei.dubbo.consumer
        
#    references:
#      - client: 
#        interface: 
#        interface-class: 
#        protocol: 
#        url: 
#        methods:
#          - 
#        consumer:
#          default:  