application:
  version: @project.version@
spring:
  profiles:
    active: @service.env@ #取配置文件
  dubbox:
    scan: com.ybveg.govx.controller
    registry:
      protocol: zookeeper
      address: zookeeper://192.168.1.8:2181
      client: curator
    protocols:
      - name: dubbo
        serialization: kryo
        optimizer: com.ybveg.govx.serialize.SerializationOptimizerImpl
    application:
      name: prota-web@project.version@
      owner: zhangbinbin
auth:
  module:
    scan: com.ybveg.govx.controller
  token:
    expire: @token.expire@
    refresh-expire: @token.refresh-expire@
    secert: @token.secert@
    issuer: @token.issuer@